### ISSUE TITLE
Website not rendering due to TypeError: Value of "this" must be of type URLSearchParams

### ISSUE THREAD

**Issue by eurunuela** [executablebooks/mystjs#390]
### What version of `mystjs` are you using?

v0.1.29

### How did you install myst?

npm

### What operating system are you using?

Mac

### Which area is this feature request for?

Command Line Interface

### Describe the Bug

I get this error when I use `myst start`:

```
TypeError: Value of "this" must be of type URLSearchParams
    at new NodeError (node:internal/errors:399:5)
    at Proxy.set (node:internal/url:519:13)
    at Proxy.<anonymous> (/Users/eurunuela/GitHub/papers_msPFM/_build/templates/site/myst/book-theme/node_modules/@remix-run/web-fetch/src/headers.js:124:44)
    at createRemixHeaders (/Users/eurunuela/GitHub/papers_msPFM/_build/templates/site/myst/book-theme/node_modules/@remix-run/express/dist/server.js:57:17)
    at createRemixRequest (/Users/eurunuela/GitHub/papers_msPFM/_build/templates/site/myst/book-theme/node_modules/@remix-run/express/dist/server.js:72:14)
    at /Users/eurunuela/GitHub/papers_msPFM/_build/templates/site/myst/book-theme/node_modules/@remix-run/express/dist/server.js:37:21
    at /Users/eurunuela/GitHub/papers_msPFM/_build/templates/site/myst/book-theme/node_modules/@remix-run/serve/dist/index.js:47:7
    at Layer.handle [as handle_request] (/Users/eurunuela/GitHub/papers_msPFM/_build/templates/site/myst/book-theme/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/eurunuela/GitHub/papers_msPFM/_build/templates/site/myst/book-theme/node_modules/express/lib/router/route.js:144:13)
    at next (/Users/eurunuela/GitHub/papers_msPFM/_build/templates/site/myst/book-theme/node_modules/express/lib/router/route.js:140:7)
```

### Expected Behavior

The website should render when using `myst start`.

**Comment by rowanc1** [comment]
I am having a bit of trouble reproducing this locally. Could you try re-installing the template with:

```bash
myst clean --templates
```

The next time you run `myst start` it should pull in the latest template. We certainly need versions on the template to help with tracking these issues down, but not quite there yet. :)

**Comment by eurunuela** [comment]
Forgot to mention this worked.
